Update to VIB. New version 8.4
> Corrected bug where a non-existent file was not recognized properly.
> Added a check so if a directory, block, or character device is attempted to be edited, it will warn the user and exit
> Simplified some internal variables
> Corrected log and temp file location errors.
> Changed TMPDIR to /tmp/vib_cache instead of just /tmp by default

diff --git a/vib b/vib
--- a/vib
+++ b/vib
@@ -1,6 +1,6 @@
 #!/bin/bash
 ###################################################################
-#LAST MODIFIED: 2022-06-07T13:57:14
+#LAST MODIFIED: 2022-06-08T12:18:33
 #USING [VIB] https://github.com/hoppyhedgehog/vib
 ###################################################################
 # DOCUMENTATION/ LOCATION: https://github.com/hoppyhedgehog/vib
@@ -33,7 +33,7 @@
 #
 ###################################################################
 #
-VERSION=8.3
+VERSION=8.4
 #
 ###################################################################
 PS4='${LINENO}: '
@@ -51,16 +51,10 @@ AUTHOR="bpatridge@tintri.com"
 
 
 ###################################################################
-# DEFAULT BASE DIRECTORY FOR VIB [/usr/local ]
+# DEFAULT 'bin' LOCATION OF VIB [ /usr/local/bin]
 #       However it may be changed to /opt or any other location
 ###################################################################
-BASEDIR=/usr/local
-
-###################################################################
-# DEFAILT 'bin' LOCATION OF VIB [$BASEDIR/bin]
-#       However it may be changed to /opt or any other location
-###################################################################
-VIB_DEFAULT_LOCATION=$BASEDIR/bin
+VIB_DEFAULT_LOCATION=/usr/local/bin
 ###################################################################
 
 
@@ -120,7 +114,9 @@ VIB_BINARY=$VIB_DEFAULT_LOCATION/vib
 #
 #
 # Specify the fully qualified path to the backup
-# directory. (ex) /opt/vib
+# directory. 
+#
+# DEFAULT:		/opt/vib/backups
 #
 # *note1: Do not use a trailing slash
 # *note2: Ensure the path is prefixed with a slas
@@ -129,7 +125,7 @@ VIB_BINARY=$VIB_DEFAULT_LOCATION/vib
 #
 ###################################################################
 
-BACKUP_DIRECTORY=$BASEDIR/${SCRIPT}_backups
+BACKUP_DIRECTORY=/opt/vib/backups
 
 ###################################################################
 # PROMPTS: Do not prompt to commit changes
@@ -176,14 +172,9 @@ USEDIR=0
 
 
 ###################################################################
-# MAIN LOG BASE DIRECTORY FOR VIB
+# MAIN VIB LOG DIRECTORY FOR 
 ###################################################################
-LOGDIR="$BASEDIR/logs"
-
-###################################################################
-# MAIN VIB LOG DIRECTORY
-###################################################################
-VIBLOGS=$LOGDIR/${SCRIPT}
+LOGDIR="/var/log/${SCRIPT}"
 
 ###################################################################
 # LOG ALL Output
@@ -202,13 +193,14 @@ LOGALL=1
 ###################################################################
 
 
-LOGFILE="$VIBLOGS/vib-history.$(date '+%Y-%m').log"
+LOGFILE="$LOGDIR/vib-history.$(date '+%Y-%m').log"
 
 
 ###################################################################
 # TEMP DIRECTORY FOR VIB CACHE FILES
+# DEFAULT:	/tmp/vib_cache
 ###################################################################
-TMPDIR=$BASEDIR/tmp
+TMPDIR=/tmp/vib_cache
 
 
 ##################################################################
@@ -382,7 +374,7 @@ fi
 ###################################################################
 writelog()
 {
-        local LOGDATE=`date '+%Y-%m-%dT%H:%M:%S.%3'`
+        local LOGDATE=`date '+%Y-%m-%dT%H:%M:%S.%N'`
         local user=`echo $MYID |tr "[:upper:]" "[:lower:]"`
 	local arg="$2"
 
@@ -445,7 +437,6 @@ f_md(){
 
 f_md $TMPDIR
 f_md $LOGDIR 
-f_md $VIBLOGS 
 
 ###################################################################
 # Function to 'stat' a file
@@ -477,20 +468,20 @@ statfile() {
 }
 	
 ###################################################################
-if [ $(statfile $VIBLOGS perm) != "6777" ]; then
-        chmod -R 6777 $VIBLOGS  >/dev/null 2>&1
+if [ $(statfile $LOGDIR perm) != "6777" ]; then
+        chmod -R 6777 $LOGDIR  >/dev/null 2>&1
 fi
 
 ###################################################################
-if [ ! -f $VIB_BINARY ]; then
+if [ ! -f $VIB_BINARY ] || [ ! -L $VIB_BINARY ]; then
         writelog $LINE 0
         writelog "ERROR: Expected to find [vib] in the default location: ${VIB_BINARY}. " 0
         writelog "Please edit vib configuration. To reflect the correct location." 0
         writelog $LINE 0
         exit 1
 fi
-if [ ! -d $VIBLOGS ]; then
-        writelog "ERROR: Unable to create $VIBLOGS." 0
+if [ ! -d $LOGDIR ]; then
+        writelog "ERROR: Unable to create $LOGDIR." 0
         exit 1
 fi
 ###################################################################
@@ -503,8 +494,14 @@ if [ -z "$MYID" ]; then
 	MYID=$(whoami |tr "[:upper:]" "[:lower:]")
 fi
 ###################################################################
+# STRIP BACKSLASH FROM BACKUP_DIRECTORY IF IT EXISTS
+###################################################################
+BACKUP_DIRECTORY=$(echo $BACKUP_DIRECTORY|sed 's:/*$::')
+
+###################################################################
 # VERIFY BACKUP_DIRECTORY EXISTS
 ###################################################################
+
 f_md $BACKUP_DIRECTORY
 
 ###################################################################
@@ -526,11 +523,11 @@ YEARMONTH=$(date '+%Y%m')
 # Verify and setthe VIB LOG HISTORY FILE
 #
 ###################################################################
-if [ $(statfile $VIBLOGS perm) != "6777" ]; then
-        chmod -R 6777 $VIBLOGS  >/dev/null 2>&1
+if [ $(statfile $LOGDIR perm) != "6777" ]; then
+        chmod -R 6777 $LOGDIR  >/dev/null 2>&1
 fi
 
-LOGFILE="$VIBLOGS/vib-history.$YEARMONTH.log"
+LOGFILE="$LOGDIR/vib-history.$YEARMONTH.log"
 
 
 ###################################################################
@@ -538,6 +535,10 @@ LOGFILE="$VIBLOGS/vib-history.$YEARMONTH.log"
 ###################################################################
 f_md "/var/tmp"
 NOVIB=/var/tmp/.novib
+NEWFILE=0					# variable to determine
+						# if file is new or not
+						# 0 = not newfile
+						# 1 = newfile
 ###################################################################
 NOTIME=/var/tmp/.vib.notime
 ###################################################################
@@ -630,18 +631,27 @@ usage() {
 echo $LINE
 echo "[V][I] [B]ackup Wrapper"
 echo "by $AUTHOR v$VERSION"
-echo $VIB
+echo $LINE
 echo "usage:   
-  # vi [-e|-d|-l|-n|-r|-t|-x|-v]  <file>
-	-e Enable VIB
-	-d Disable VIB
-	-l Enable add Last Modification Date (Default is Enabled)
-	-n Disable all Last Modification prepending
-	-r Uninstall-Reset the alias to default
-	-t FORCE Enable add Last Modification Date to <file>
-	   *note: Default for any scripts
-	-x Set permissions to 755
-	-v Verbose (debug) output"
+  # vi [-e|-d|-l|-n|-r|-t|-x|-u|-v]  <file>
+	-e 	Enable VIB
+	-d 	Disable VIB
+	-l 	Enable add Last Modification Date (Default is Enabled)
+	-n 	Disable all Last Modification prepending
+	-r 	Uninstall-Reset the alias to default
+	-t 	FORCE Enable add Last Modification Date to <file>
+	   	*note: Default for any scripts
+	-x 	Set permissions to 755
+	-v 	Verbose (debug) output"
+echo $LINE
+echo "Directories Used"
+echo "Logs:		$LOGDIR"
+if [ $USEDIR == 0 ]; then
+	echo "Backups:	$BACKUP_DIRECTORY"
+else
+	echo -e "Backups:	$BACKUP_DIRECTORY \t# Based on CURRENT Directory"
+fi
+echo "Temp Dir:	$TMPDIR"
 echo $LINE
 
 exit
@@ -776,20 +786,26 @@ check_date_change() {
 	fi
 }
 ###################################################################
+###################################################################
 # PROCESS COMMAND LINE ARGUMENTS
 ###################################################################
-
-while getopts ':hnletxvdr' OPT_NAME; do
+arg_list=()
+while getopts ':hnletxvdrT' OPT_NAME; do
    case $OPT_NAME in
       (\?)
-         usage
-         exit 0;;
+         	usage
+         	exit 0;;
       ("h")
-        usage 
-         exit 0;;
-      ("x")  make_executable=1;;
-      ("v")  set -x ;;
-      ("t")  forcedate=1;;
+        	usage 
+         	exit 0;;
+      ("x")  	make_executable=1
+		arg_list+=("x");;
+      ("v")  	set -x 
+		arg_list+=("v");;
+      ("T")  	devtest=1; 		# HIDDEN OPTION ONLY TO TEST
+		arg_list+=("T");;
+      ("t")  	forcedate=1
+		arg_list+=("t");;
       ("l") 
 		echo $LINE
 		echo "ENABLED ALL PREPENDING OF"
@@ -852,6 +868,9 @@ if [ $USEDIR != 1 ] && [ $BACKUP_DIRECTORY == ".vib_backup" ]; then
 	exit;
 fi
 ###################################################################
+if [ ! -z $devtest ]; then
+	set -x
+fi
 ###################################################################
 m_readlink() {
     [ "." = "${1}" ] && n=${PWD} || n=${1}; while nn=$( readlink -n "$n" ); do n=$nn; done; echo "$n"
@@ -892,19 +911,41 @@ ARGUMENTS=("$@")				#ZERO ARG ARRAY
 TOTAL_ARGUMENTS="${#ARGUMENTS[@]}"			
 ca=0
 for i in "${ARGUMENTS[@]}"; do
-	if [ -L "$i" ]; then
-		SOFT_LINK_FILE_NAME=$(basename "$i")
-		FILE_DIRECTORY=$(read_dirpath "$i")
-		TF=$(read_filename "$i")
-		FILE_NAME=$(basename $TF)
-		SOFT_LINK=1
-		((ca++))
-	elif [ -f "$i" ]; then
-		FILE_NAME=$(basename "$i")
-		FILE_DIRECTORY=$(read_dirpath "$i")
-		((ca++))
+	if [[ ( ${#arg_list[@]} -gt 0 ) &&  ($i =~ ${arg_list[@]}) ]]; then
+			foundarg=1
+	else
+		if [ -L "$i" ]; then
+			SOFT_LINK_FILE_NAME=$(basename "$i")
+			FILE_DIRECTORY=$(read_dirpath "$i")
+			TF=$(read_filename "$i")
+			FILE_NAME=$(basename $TF)
+			SOFT_LINK=1
+			((ca++))
+		elif [ -f "$i" ]; then
+			FILE_NAME=$(basename "$i")
+			FILE_DIRECTORY=$(read_dirpath "$i")
+			((ca++))
+		else
+			if [ $(echo $i|grep -q "/";echo $?) == 0 ]; then	
+				FILE_NAME=$(basename "$i")
+				FILE_DIRECTORY=$(read_dirpath "$i")
+			else
+				FILE_NAME=$i
+				FILE_DIRECTORY=$(read_dirpath "$i")
+			fi
+		fi
 	fi
+		
 done
+if [ ! -z $devtest ]; then
+	echo "FILE_NAME=$FILE_NAME"
+	echo "FILE_DIR=$FILE_DIRECTORY"
+fi
+if [ -z $FILE_NAME ]; then
+	echo $LINE
+	echo "ERROR: Unable to find File Name"
+	exit 1
+fi
 
 if [ $ca -gt 1 ]; then
 	echo "ERROR: You can only specify ONE File"
@@ -915,12 +956,12 @@ if [ "$FILE_DIRECTORY" == "/" ]; then
 	FILE_DIRECTORY=
 fi
 #----
-#NAME=${ARGUMENTS[${#ARGUMENTS[@]}-1]}
-#FILE_NAME=$(basename $NAME)
-#FILE_DIRECTORY=$(read_dirpath "$NAME")
-#----
-ORIGINAL_USER_SUPPLIED_FILE_EPOCH=$(statfile "$FILE_DIRECTORY/$FILE_NAME" epoch)
-ORIGINAL_USER_SUPPLIED_FILE_SIZE=$(statfile "$FILE_DIRECTORY/$FILE_NAME" size)
+if [ -f  "$FILE_DIRECTORY/$FILE_NAME" ]; then
+	ORIGINAL_USER_SUPPLIED_FILE_EPOCH=$(statfile "$FILE_DIRECTORY/$FILE_NAME" epoch)
+	ORIGINAL_USER_SUPPLIED_FILE_SIZE=$(statfile "$FILE_DIRECTORY/$FILE_NAME" size)
+else
+	NEWFILE=1
+fi
 ###################################################################
 # Create backup directory
 ###################################################################
@@ -1041,6 +1082,27 @@ check_ifis_script() {
 }
 
 ###################################################################
+# IF A DIRECTORY IS SUPPLIED BY MISTAKE INFORM THE USER
+###################################################################
+if [ -d "$FILE_DIRECTORY/$FILE_NAME" ]; then
+	echo $LINE
+	echo "ERROR: $FILE_DIRECTORY/$FILE_NAME is a Directory not a file"
+	echo $LINE
+	exit 1
+fi
+	
+###################################################################
+# CHECK FILE TYPE
+###################################################################
+check_valid_filetype() {
+	for ftype in "block" "character"; do
+		if [ $(stat -c %F "$FILE_DIRECTORY/$FILE_NAME"|grep -q $ftype ;echo $?) == 0 ]; then
+			echo -e"$LINE\nERROR: $FILE_DIRECTORY/$FILE_NAME is a [$ftype] file\n$LINE"
+			exit 1
+		fi
+	done
+}
+###################################################################
 # Determine if the file type is of a script and should include the date/modification time
 ###################################################################
 
@@ -1060,7 +1122,18 @@ file_not_exist() {
         exit 1
 }
 ###################################################################
-if [ -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
+# Display file we are about to edit IF devtest option is given
+###################################################################
+if [ ! -z $devtest ]; then
+	check_valid_filetype
+	echo "$VI_BINARY $FILE_DIRECTORY/$FILE_NAME"
+	exit
+fi
+###################################################################
+# IF DIRECTORY AND FILE EXIST AND IT IS NOT A NEWFILE
+###################################################################
+if [ -f "$FILE_DIRECTORY/$FILE_NAME" ] && [ $NEWFILE == 0 ]; then
+	check_valid_filetype
 	if  [ $(statfile $FILE_DIRECTORY/$FILE_NAME size) -gt $MAX_USER_SUPPLIED_FILE_SIZE ]; then
 		writelog "Unable to backup file as MAX_USER_SUPPLIED_FILE_SIZE -->$MAX_USER_SUPPLIED_FILE_SIZE"
 		sleep 1
@@ -1069,7 +1142,7 @@ if [ -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
 	fi
 fi
 
-# IF the file does not exist (i.e. path to file)
+# IF the file does not exist (i.e. path to file) then create new file
 if [ ! -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
 	if [[ (( -n "$2" ) && ( "$2" = "n" )) || ( $MAKE_NEW == 1 )  ]]; then
 		writelog "Creating $FILE_NAME"
@@ -1086,13 +1159,21 @@ if [ ! -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
 	fi
 
 else
-
+	# IF the file DOES Exist AND there is no initial backup file then create a backup file
 	if [ ! -f "$BACKUP_DIRECTORY/${FILE_NAME}.${MYID}.1" ] && [ -z $nobackup ]; then 
 		cp -p -f "$FILE_DIRECTORY/$FILE_NAME" "$BACKUP_DIRECTORY/${FILE_NAME}.${MYID}.1" > /dev/null 2>&1
 	fi
+
+	# Copy file to TMPFILE for backup purposes
 	cp -pf "$FILE_DIRECTORY/$FILE_NAME" "$TMPFILE" > /dev/null 2>&1
+	
+	# verify file is a valid filetype
+	check_valid_filetype
+
+	# VI Edit the file
 	"$VI_BINARY" "$FILE_DIRECTORY/$FILE_NAME"
 
+	# IF File still does not exist after editing the file then notify user
 	if [ ! -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
 		file_not_exist
 	fi
