Update vib
Vib v8.8

diff --git a/vib b/vib
--- a/vib
+++ b/vib
@@ -1,11 +1,13 @@
 #!/bin/bash
 ###################################################################
-#LAST MODIFIED: 2022-06-08T12:18:33
+#LAST_MODIFIED: 2022-08-10T09:59:25
+###################################################################
 #USING [VIB] https://github.com/hoppyhedgehog/vib
 ###################################################################
 # DOCUMENTATION/ LOCATION: https://github.com/hoppyhedgehog/vib
 ###################################################################
 # *Note: Shell MUST be in BASH or KSH or ZSH
+###################################################################
 ###################################################################
 # -*- coding: utf-8 -*-
 #
@@ -33,7 +35,7 @@
 #
 ###################################################################
 #
-VERSION=8.4
+VERSION=8.8
 #
 ###################################################################
 PS4='${LINENO}: '
@@ -473,7 +475,14 @@ if [ $(statfile $LOGDIR perm) != "6777" ]; then
 fi
 
 ###################################################################
-if [ ! -f $VIB_BINARY ] || [ ! -L $VIB_BINARY ]; then
+if [  -f $VIB_BINARY ]; then
+        found_vib=1
+else
+        if [ -L $VIB_BINARY ]; then
+                found_vib=1
+        fi
+fi
+if [ -z $found_vib ]; then
         writelog $LINE 0
         writelog "ERROR: Expected to find [vib] in the default location: ${VIB_BINARY}. " 0
         writelog "Please edit vib configuration. To reflect the correct location." 0
@@ -535,7 +544,7 @@ LOGFILE="$LOGDIR/vib-history.$YEARMONTH.log"
 ###################################################################
 f_md "/var/tmp"
 NOVIB=/var/tmp/.novib
-NEWFILE=0					# variable to determine
+NOT_NEWFILE=0					# variable to determine
 						# if file is new or not
 						# 0 = not newfile
 						# 1 = newfile
@@ -633,7 +642,9 @@ echo "[V][I] [B]ackup Wrapper"
 echo "by $AUTHOR v$VERSION"
 echo $LINE
 echo "usage:   
-  # vi [-e|-d|-l|-n|-r|-t|-x|-u|-v]  <file>
+  # vi [-b|-e|-d|-l|-n|-r|-t|-x|-u|-v]  <file>
+	-b 	Create Version backup
+		(if 'VERSION=' Variable is atop script)
 	-e 	Enable VIB
 	-d 	Disable VIB
 	-l 	Enable add Last Modification Date (Default is Enabled)
@@ -786,91 +797,15 @@ check_date_change() {
 	fi
 }
 ###################################################################
-###################################################################
-# PROCESS COMMAND LINE ARGUMENTS
-###################################################################
-arg_list=()
-while getopts ':hnletxvdrT' OPT_NAME; do
-   case $OPT_NAME in
-      (\?)
-         	usage
-         	exit 0;;
-      ("h")
-        	usage 
-         	exit 0;;
-      ("x")  	make_executable=1
-		arg_list+=("x");;
-      ("v")  	set -x 
-		arg_list+=("v");;
-      ("T")  	devtest=1; 		# HIDDEN OPTION ONLY TO TEST
-		arg_list+=("T");;
-      ("t")  	forcedate=1
-		arg_list+=("t");;
-      ("l") 
-		echo $LINE
-		echo "ENABLED ALL PREPENDING OF"
-		echo "LAST MODIFICATION TIME"
-		echo $LINE
-	        vib_cleanup $NOTIME
-		exit
-	     	;;
-      ("e")  rm -f $NOVIB >/dev/null 2>&1
-		echo $LINE
-		echo "ENABLED VIB"
-		echo "REMOVED FILE: $NOVIB"
-		echo $LINE
-		setvib
-		exit;;
-      ("d")  touch $NOVIB
-		echo $LINE
-		echo "DISABLED VIB"
-		echo "CREATED FILE: $NOVIB"
-		echo "To re-enable VIB: vib -S"
-		echo $LINE
-		exit;;
-      ("n")  touch $NOTIME
-		echo $LINE
-		echo "DISABLED ALL PREPENDING OF"
-		echo "LAST MODIFICATION TIME"
-		echo $LINE
-		exit;;
-      ("r")  
-		$SED -i "s:alias vi=.*$:alias vi=\"/usr/bin/vim\":g" $HOME/.bashrc
-		source $HOME/.bashrc;
-		echo $LINE
-		echo "Reset vi back using:"
-		echo "	 # alias vi=/usr/bin/vim' "
-		echo $LINE
-		unalias vi 2>/dev/null
-		exit;;
-	("*")  usage;;
-   esac
-done
-
-if [ ! -z $setvib ]; then
-	if [ $(grep -q "alias vi=.*vib" $HOME/.bashrc; echo $?) != 0 ]; then
-		$SED -i  "s:alias vi=.*$:alias vi=\"$VIB_BINARY\":g" $HOME/.bashrc
-		source $HOME/.bashrc
+validate_version() {
+	local ver="$1"
+	rx='^([0-9]+\.){0,2}(\*|[0-9]+)(\-.*){0,1}$'
+	if [[ $ver =~ $rx ]]; then
+		echo 0
+	else
+		echo 1
 	fi
-fi
-
-
-if [ -f $TMPFILE ]; then
-	vib_cleanup
-fi
-
-if [ -z $1 ]; then
-	usage
-fi
-
-if [ $USEDIR != 1 ] && [ $BACKUP_DIRECTORY == ".vib_backup" ]; then
-	echo "ERROR: BACKUP_DIRECTORY cannot equal .vib_backup when USEDIR is set ..."
-	exit;
-fi
-###################################################################
-if [ ! -z $devtest ]; then
-	set -x
-fi
+}
 ###################################################################
 m_readlink() {
     [ "." = "${1}" ] && n=${PWD} || n=${1}; while nn=$( readlink -n "$n" ); do n=$nn; done; echo "$n"
@@ -906,37 +841,120 @@ read_dirpath () {
 ###################################################################
 ###################################################################
 ###################################################################
+
 shopt -s extglob
 ARGUMENTS=("$@")				#ZERO ARG ARRAY
 TOTAL_ARGUMENTS="${#ARGUMENTS[@]}"			
 ca=0
-for i in "${ARGUMENTS[@]}"; do
-	if [[ ( ${#arg_list[@]} -gt 0 ) &&  ($i =~ ${arg_list[@]}) ]]; then
-			foundarg=1
-	else
-		if [ -L "$i" ]; then
-			SOFT_LINK_FILE_NAME=$(basename "$i")
-			FILE_DIRECTORY=$(read_dirpath "$i")
-			TF=$(read_filename "$i")
-			FILE_NAME=$(basename $TF)
-			SOFT_LINK=1
-			((ca++))
-		elif [ -f "$i" ]; then
-			FILE_NAME=$(basename "$i")
-			FILE_DIRECTORY=$(read_dirpath "$i")
-			((ca++))
-		else
-			if [ $(echo $i|grep -q "/";echo $?) == 0 ]; then	
-				FILE_NAME=$(basename "$i")
-				FILE_DIRECTORY=$(read_dirpath "$i")
-			else
-				FILE_NAME=$i
-				FILE_DIRECTORY=$(read_dirpath "$i")
-			fi
-		fi
-	fi
+arg_list=()
+for (( i = 0; i < ${#ARGUMENTS[*]}; ++ i )); do
+	arg=${ARGUMENTS[$i]}
+		case "$arg" in
+		      ('-?')
+				usage
+				exit 0;;
+		      ("-b")     backup_version=1;;
+		      ("-h")
+				usage
+				exit 0;;
+		      ("-x")     make_executable=1
+				arg_list+=("x");;
+		      ("--ver"|"--version")     usage;;
+		      ("-v")     set -x
+				arg_list+=("v");;
+		      ("-T")     devtest=1;              # HIDDEN OPTION ONLY TO TEST
+				arg_list+=("T");;
+		      ("-t")     forcedate=1
+				arg_list+=("t");;
+		      ("-l")
+				echo $LINE
+				echo "ENABLED ALL PREPENDING OF"
+				echo "LAST MODIFICATION TIME"
+				echo $LINE
+				vib_cleanup $NOTIME
+				exit
+				;;
+		      ("-e")  rm -f $NOVIB >/dev/null 2>&1
+				echo $LINE
+				echo "ENABLED VIB"
+				echo "REMOVED FILE: $NOVIB"
+				echo $LINE
+				setvib
+				exit;;
+		      ("-d")  touch $NOVIB
+				echo $LINE
+				echo "DISABLED VIB"
+				echo "CREATED FILE: $NOVIB"
+				echo "To re-enable VIB: vib -S"
+				echo $LINE
+				exit;;
+		      ("-n")  touch $NOTIME
+				echo $LINE
+				echo "DISABLED ALL PREPENDING OF"
+				echo "LAST MODIFICATION TIME"
+				echo $LINE
+				exit;;
+		      ("-r")
+				$SED -i "s:alias vi=.*$:alias vi=\"/usr/bin/vim\":g" $HOME/.bashrc
+				source $HOME/.bashrc;
+				echo $LINE
+				echo "Reset vi back using:"
+				echo "   # alias vi=/usr/bin/vim' "
+				echo $LINE
+				unalias vi 2>/dev/null
+				exit;;
+			*)
+
+				if [ -L "$arg" ]; then
+					SOFT_LINK_FILE_NAME=$(basename "$arg")
+					FILE_DIRECTORY=$(read_dirpath "$arg")
+					TF=$(read_filename "$arg")
+					FILE_NAME=$(basename $TF)
+					SOFT_LINK=1
+					((ca++))
+				elif [ -f "$arg" ]; then
+					FILE_NAME=$(basename "$arg")
+					FILE_DIRECTORY=$(read_dirpath "$arg")
+					((ca++))
+				else
+					if [ $(echo $arg|grep -q "/";echo $?) == 0 ]; then	
+						FILE_NAME=$(basename "$arg")
+						FILE_DIRECTORY=$(read_dirpath "$arg")
+					else
+						FILE_NAME=$arg
+						FILE_DIRECTORY=$(read_dirpath "$arg")
+					fi
+				fi
+				;;
+
+			esac
 		
 done
+#--------------------------------------------------------------
+if [ ! -z $setvib ]; then
+        if [ $(grep -q "alias vi=.*vib" $HOME/.bashrc; echo $?) != 0 ]; then
+                $SED -i  "s:alias vi=.*$:alias vi=\"$VIB_BINARY\":g" $HOME/.bashrc
+                source $HOME/.bashrc
+        fi
+fi
+
+
+if [ -f $TMPFILE ]; then
+        vib_cleanup
+fi
+
+if [ -z $1 ]; then
+        usage
+fi
+
+if [ $USEDIR != 1 ] && [ $BACKUP_DIRECTORY == ".vib_backup" ]; then
+        echo "ERROR: BACKUP_DIRECTORY cannot equal .vib_backup when USEDIR is set ..."
+        exit;
+fi
+#--------------------------------------------------------------
+if [ ! -z $devtest ]; then
+        set -x
+fi                
 if [ ! -z $devtest ]; then
 	echo "FILE_NAME=$FILE_NAME"
 	echo "FILE_DIR=$FILE_DIRECTORY"
@@ -960,7 +978,7 @@ if [ -f  "$FILE_DIRECTORY/$FILE_NAME" ]; then
 	ORIGINAL_USER_SUPPLIED_FILE_EPOCH=$(statfile "$FILE_DIRECTORY/$FILE_NAME" epoch)
 	ORIGINAL_USER_SUPPLIED_FILE_SIZE=$(statfile "$FILE_DIRECTORY/$FILE_NAME" size)
 else
-	NEWFILE=1
+	NOT_NEWFILE=1
 fi
 ###################################################################
 # Create backup directory
@@ -968,7 +986,6 @@ fi
 f_md $BACKUP_DIRECTORY
 ###################################################################
 ###################################################################
-# edit file using VI_BINARY
 ###################################################################
 # if USEDIR is set to 1, then set the FILE_NAME
 # to the INPUT variable and change the assign
@@ -1015,7 +1032,7 @@ add_change_date(){
 			fi
 
 		if [ $lastmod_line -gt  0 ]; then
-			$SED -i $msedvar  "${lastmod_line}s|.*|\#LAST MODIFIED: $mod_date|" "$FILE_DIRECTORY/$FILE_NAME"
+			$SED -i $msedvar  "${lastmod_line}s|.*|\#LAST_MODIFIED: $mod_date|" "$FILE_DIRECTORY/$FILE_NAME"
 			if [ $ENABLE_VIB_COMMENT == 0 ]; then
 				if [ $comment_line -gt 0 ]; then
 					$SED -i $msedvar  "${comment_line}s|.*|\#$VIB_COMMENT|" "$FILE_DIRECTORY/$FILE_NAME"
@@ -1024,25 +1041,25 @@ add_change_date(){
 				fi
 			fi
 
-			writelog "Updated -->  LAST MODIFIED: $mod_date" 
+			writelog "Updated -->  LAST_MODIFIED: $mod_date" 
 
 		#---------------------------------------------------------------------
 		# IF there is no last modify, forcedate is set and file is NOT a script
 		# OR if there is no last modify, and file is NOT a script
 		#---------------------------------------------------------------------
 		elif [[  ( ( $lastmod_line == 0 ) && ( ! -z $forcedate ) && ( -z $script ) ) || ( ( $lastmod_line == 0 ) && ( -z $script) )  ]];  then
-			$SED -i $msedvar "1i$COMMENT_LINE\n\#LAST MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
-			writelog "Added atop file -->  LAST MODIFIED: $mod_date" 
+			$SED -i $msedvar "1i$COMMENT_LINE\n\#LAST_MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
+			writelog "Added atop file -->  LAST_MODIFIED: $mod_date" 
 
 		#---------------------------------------------------------------------
 		# IF there is no last modify, and file  IS A SCRIPT
 		#---------------------------------------------------------------------
 		elif [ $lastmod_line == 0 ] && [ ! -z $script ]; then
-			$SED -i $msedvar "2i$COMMENT_LINE\n\#LAST MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
-			writelog "Added atop file -->  LAST MODIFIED: $mod_date" 
+			$SED -i $msedvar "2i$COMMENT_LINE\n\#LAST_MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
+			writelog "Added atop file -->  LAST_MODIFIED: $mod_date" 
 		else
-			$SED -i $msedvar "${lastmod_line}i$COMMENT_LINE\n\#LAST MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
-			writelog "Added atop file -->  LAST MODIFIED: $mod_date" 
+			$SED -i $msedvar "${lastmod_line}i$COMMENT_LINE\n\#LAST_MODIFIED: $mod_date\n$LC" "$FILE_DIRECTORY/$FILE_NAME"
+			writelog "Added atop file -->  LAST_MODIFIED: $mod_date" 
 		fi
 
 		#---------------------------------------------------------------------
@@ -1058,7 +1075,7 @@ add_change_date(){
 # checking to see if file is a script, and if so, then add file modification date
 ###################################################################
 check_lastmod_header() {
-	head -5 "$FILE_DIRECTORY/$FILE_NAME" |awk 'BEGIN{c=0} $0 ~ /LAST MODIFIED/ {c=NR}END{print c}'
+	head -5 "$FILE_DIRECTORY/$FILE_NAME" |awk 'BEGIN{c=0} $0 ~ /LAST_MODIFIED/ {c=NR}END{print c}'
 }
 
 check_comment_header() {
@@ -1069,7 +1086,14 @@ check_comment_header() {
 # check to see if the file is a script
 ###################################################################
 check_ifis_script() {
-	if [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q '\#\!.*bin.*[k|tc|z|c|ba]sh'; echo $? ) == 0 ] || [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q '\#\!.*perl'; echo $? ) == 0 ] || [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q "\#\!.*python"; echo $? ) == 0 ]; then
+	if [ $(echo $FILE_NAME|grep -q "\.cgi";echo $?) == 0 ]; then
+		script=
+		noinsert_header=1
+		lastmod_line=0;
+		comment_line=0;
+touch /tmp/bcgi
+
+	elif [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q '\#\!.*bin.*[k|tc|z|c|ba]sh'; echo $? ) == 0 ] || [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q '\#\!.*perl'; echo $? ) == 0 ] || [ $(head -1 "$FILE_DIRECTORY/$FILE_NAME"|grep -q "\#\!.*python"; echo $? ) == 0 ]; then
 		script=1	
 	else
 		script=
@@ -1105,13 +1129,11 @@ check_valid_filetype() {
 ###################################################################
 # Determine if the file type is of a script and should include the date/modification time
 ###################################################################
-
 if [ ! -f $NOTIME ] && [ -f "$FILE_DIRECTORY/$FILE_NAME" ]; then
-	lastmod_line=$(check_lastmod_header)		# check to see if the LAST MODIFIED time is atop the file
+	lastmod_line=$(check_lastmod_header)		# check to see if the LAST_MODIFIED time is atop the file
 	comment_line=$(check_comment_header)		# check to see if the optional VIB HEADER is atop the file
 	check_ifis_script
 fi
-
 ###################################################################
 #
 # check the filesize to see if it exceeds the max file size to edit and backup a file
@@ -1130,9 +1152,30 @@ if [ ! -z $devtest ]; then
 	exit
 fi
 ###################################################################
-# IF DIRECTORY AND FILE EXIST AND IT IS NOT A NEWFILE
+# IF VERSION BACKUP OPTION IS USED THEN LOOK FOR IN THE FILE THE
+# FIRST MATCH OF 'VERSION=' AND USE THAT VALUE 
 ###################################################################
-if [ -f "$FILE_DIRECTORY/$FILE_NAME" ] && [ $NEWFILE == 0 ]; then
+if [ ! -z $backup_version ]; then
+	if [ -f "$FILE_DIRECTORY/$FILE_NAME" ] && [ $NOT_NEWFILE == 0 ]; then
+		check_ver=$(grep -m1 "^VERSION=" "$FILE_DIRECTORY/$FILE_NAME"|cut -d= -f2-|awk '{gsub(/[[:blank:]]/,"");print}')
+		if [ ! -z "$check_ver" ]; then
+			if [ $(validate_version $check_ver) == 0 ]; then
+				version_line=$(grep -m1 "^VERSION=" "$FILE_DIRECTORY/$FILE_NAME" |awk 'BEGIN{c=0} $0 ~ /VERSION/ {c=NR}END{print c}')
+				writelog "Backing up ${FILE_NAME} --> ${FILE_NAME}.$check_ver"
+				cp -pf  "$FILE_DIRECTORY/$FILE_NAME" "$FILE_DIRECTORY/${FILE_NAME}.$check_ver"	 2>/dev/nul
+			else
+				writelog "Unable to Validate 'VERSION=$check_ver' for $FILE_DIRECTORY/${FILE_NAME}. Skipping"
+			fi
+		else
+				writelog "Unable to find 'VERSION=' in $FILE_DIRECTORY/${FILE_NAME}. Skipping"
+		fi
+	fi	
+fi	
+###################################################################
+# IF DIRECTORY AND FILE EXIST AND IT IS NOT A NOT_NEWFILE
+###################################################################
+
+if [ -f "$FILE_DIRECTORY/$FILE_NAME" ] && [ $NOT_NEWFILE == 0 ]; then
 	check_valid_filetype
 	if  [ $(statfile $FILE_DIRECTORY/$FILE_NAME size) -gt $MAX_USER_SUPPLIED_FILE_SIZE ]; then
 		writelog "Unable to backup file as MAX_USER_SUPPLIED_FILE_SIZE -->$MAX_USER_SUPPLIED_FILE_SIZE"
@@ -1335,7 +1378,7 @@ if [ ! -z $make_executable ]; then
 	chmod 755 "$FILE_DIRECTORY/$FILE_NAME"
 fi
 ###################################################################
-# Pre-Pend the LAST MODIFIED <date/time> at the beginning of the file
+# Pre-Pend the LAST_MODIFIED <date/time> at the beginning of the file
 # if the file is a perl/ksh/sh/bash script 
 # OR
 # if the '-t' argument is supplied
